#! /usr/bin/bash -v
export muse=~/repos/muse/muse
java -Xmx1024m -cp /Users/viharipiratla/repos/muse/muse/WebContent/WEB-INF/lib/opennlp-tools-1.5.3.jar:.:/Users/viharipiratla/repos/muse/muse/build/jar/muse.jar:/Users/viharipiratla/repos/muse/muse/WebContent/WEB-INF/lib/commons-logging-1.1.1.jar edu.stanford.muse.index.POS large.txt >large.POS.res